### ISSUE TITLE
Example tools code?

### ISSUE THREAD

**Issue by zvezdochiot** [whateveritech/libqct#1]
Hi @whateveritech.

Add example code for tools (encode, decode) that use `libqct.h` functions to this repository.

**Comment by whateveritech** [comment]
It is now added with a stable version, you should check it out.

**Comment by zvezdochiot** [comment]
Hi @whateveritech .

Replace:
https://github.com/whateveritech/libqct/blob/6a98c17c2636b9d8ece2627db8eb24a13193708e/examples/decode.c#L1-L4
to:
```c
#define STB_IMAGE_IMPLEMENTATION
#include "../stb/stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../stb/stb_image_write.h"
```
and:
https://github.com/whateveritech/libqct/blob/6a98c17c2636b9d8ece2627db8eb24a13193708e/examples/encode.c#L1-L4
to:
```c
#define STB_IMAGE_IMPLEMENTATION
#include "../stb/stb_image.h"
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "../stb/stb_image_write.h"
```

Good luck. :+1:
